import Head from "next/head";
import CardList from "../components/CardList";

const Home = () => {
  return (
    <>
      <Head>
        <title>Card App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <CardList />
      </main>
    </>
  );
};

export default Home;
