import Head from "next/head";
import CardList from "../components/CardList";

type HomeProps = {
  children?: any;
};

const Home: React.FunctionComponent<HomeProps> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <CardList />
      </main>
    </>
  );
};

export default Home;
